### ISSUE TITLE
Add tests for CSS variables

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#117]
```css
element {
  --main-bg-color: brown;
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables
