### ISSUE TITLE
Paths to urls within CSS likely to be busted

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#12]
If we intercept and download `https://cdn.example.com/prefix/foo.css` and that contains css like this:
```css
.selector {
  background-image: url(../path/static.png);
}
```
If that css (minified and everything) is inserted inline the HTML page, it's going to assume that the file `static.png` exists on the HTML page's domain too. 

Either print a warning. Or attempt to solve it by extrapolating the domain and prefix etc.
