### ISSUE TITLE
Strip unused keyframe animations

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#14]
If you have a keyframe, like:
```css
@keyframes cssload-global {
  0%, 100% {
    transform: rotateY(0deg);
  }
  50% {
    transform: rotateY(360deg);
  }
}
```

We should only keep it if there is a thing like this:
```css
animation: 2.3s cssload-global infinite;
```
...for example. 

Note that we can't just look for `animation`. We might also need to look for things like `-ms-animation`.

**Comment by peterbe** [comment]
Wow! I let minimalcss run against https://www.peterbe.com/search?q=found
The minimal CSS output became 44.5KB (from 491KB). I inspected it manually and noticed a laaarge about of keyframes that the rest of the CSS never uses. 
See https://gist.github.com/peterbe/dae0f4ce541fb073c2632360b2166eda for the formatted CSS. 

To make a fair comparison I minified the CSS with and without the keyframes. The size difference was huge:

* `search.min.css` - 41KB
* `search.nokeyframes.min.css` - 15KB

Granted, if the minimal CSS is inlined with the HTML and the HTML can be gzipped, the damage isn't too bad:

* `search.min.css.gz` - 6.3KB
*  `search.nokeyframes.min.css.gz` - 4.6KB

**Comment by peterbe** [comment]
After thinking about it, this got a lot more complicated. 
A very common pattern, especially for single-page-apps, is to do something like this:
```css
.loading {
  width: 11px;
  height: 7px;
  position: absolute;
  top: 50%;
  left: 50%;
  background: rgb(115, 179, 255);
  animation: cssload-grow 3.45s infinite cubic-bezier(0.53, 0.68, 0.53, 0.41);
}
@keyframes cssload-grow {
  0%,
  100% {
    transform: translateX(-19px) scaleX(0.5);
    background: rgb(115, 179, 255);
  }
  25% {
    transform: translateX(0px) scaleY(1) scaleX(5) rotateY(180deg);
    background: rgb(240, 192, 120);
  }
  50% {
    transform: translateX(19px) scaleX(0.5);
    background: rgb(115, 179, 255);
  }
  75% {
    transform: translateX(0px) scaleY(1) scaleX(5) rotateY(180deg);
    background: rgb(240, 192, 120);
  }
}
```
```html
<body>
  <div id="app">
    <div class="loading"></div>
  </div>
</body>
```
```javascript
$(function() {
  $('#app').load('/xhr');
}
```
In other words, the DOM is something like a loading animation that works as soon as the HTML and the CSS has been downloaded. Then the Javascript (downloads, parses and executes) comes along and starts some XHR or something and when the data is available, it changes the DOM drastically.

It would be a mistake to apply minimal CSS based on the fully loaded page, ONLY. So we have **two** DOMs: 
1) Before JavaScript executes
2) After JavaScript executes

Potentially we have **three** DOMs.
1) Before JavaScript executes
2) After JavaScript executes
3) After XHR requests have finished that start as soon as the page is loaded and JavaScript onload is executed. 

In its current state, `minimalcss` only [deals with point 3 and beyond](https://github.com/peterbe/minimalcss/blob/4dead07e4aa8eef429124577be1b0ba9799a8549/src/run.js#L123).
