### ISSUE TITLE
Data URLs are broken

### ISSUE THREAD

**Issue by phiresky** [peterbe/minimalcss#152]
Minimal example:

x.html
```html
<link rel=stylesheet href=x.css>

<span class="test">hi</span>
```

x.css:
```css
.test {
    background-image:url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
}
```

output:
```js
{ finalCss: '.test{background-image:url(image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7)}',
  stylesheetContents: 
   { 'http://0.0.0.0:8000/x.css': '.test {\n    background-image:url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);\n}\n' } }
```

As you can see, `url(data:image/gif;base64,` is changed to `url(image/gif;base64,` which is wrong.
