### ISSUE TITLE
[feature] Elevate @font-face declaration to the top

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#273]
So I have CRA2 project with react-snap, because CRA2 do code splitting including for styles it can include is a bit strange order, so font can get used before it is declared.

```css
.someClass { font-family: Sans Forgetica; }

...

@font { 
font-display: swap;
  font-family: "Sans Forgetica";
  font-style: normal;
  font-weight: 600;
  src: local("Sans Forgetica"), local("Sans Forgetica")
}
```
