### ISSUE TITLE
Choking on `:ActiveHover`

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#39]
Found this piece of CSS from a SemanticUI project:
```css
/*-------------------
     Active Hover
--------------------*/

a.ui.labels .active.label:hover,
a.ui.active.label:hover {
  background-color: #C8C8C8;
  border-color: #C8C8C8;
  background-image: none;
  color: rgba(0, 0, 0, 0.95);
}
.ui.labels a.active.label:ActiveHover:before,
a.ui.active.label:ActiveHover:before {
  background-color: #C8C8C8;
  background-image: none;
  color: rgba(0, 0, 0, 0.95);
}
```

minimalcss chokes on this:

```
Error: Evaluation failed: Error: Unable to querySelector('.ui.labels a.active.label:ActiveHover:before') [SyntaxError: Failed to execute 'querySelector' on 'Document': '.ui.labels a.active.label:ActiveHover:before' is not a valid selector.]
    at objsCleaned.(anonymous function).selector (<anonymous>:158:21)
    at values.filter.selectorString (<anonymous>:75:30)
    at Array.filter (<anonymous>)
    at children.filter.child (<anonymous>:71:41)
    at Array.filter (<anonymous>)
    at clean (<anonymous>:68:27)
    at cleaner (<anonymous>:105:24)
    at links.filter.forEach.stylesheet (<anonymous>:134:42)
    at Array.forEach (<anonymous>)
    at stylesheetAstObjects (<anonymous>:124:10)
    at Frame._rawEvaluate (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/FrameManager.js:250:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
