### ISSUE TITLE
Strip font-faces not used

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#55]
If you run `./bin/minimalcss.js -o /tmp/peterbe.css https://www.peterbe.com/search\?q\=css` that CSS will contain this:
```css
@font-face {
    font-family: 'Rating';
    src: url(data:application/x-font-ttf;charset=utf-8;base64,AAEAAAALAIAAAwAwT1MvMggjCBsAAAC8AAAAYGNtYXCj2pm8AAABHAAAAKRnYXNwAAAAEAAAAcAAAAAIZ[   ...15,330 bytes snipped... ]AAAAAAAAAAAAAAAAAA==) format('woff');
    font-weight: 400;
    font-style: normal
}
```
But there is NO selector that contains something like 
`font-family: Rating;`

So this font-face can be removed.
