### ISSUE TITLE
Minification with merge not working properly

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#7]
[Songsear.ch](https://songsear.ch/) uses bootstrap and when running for two different URLs it clearly fails to merge the CSS.
Consider:
```
./bin/minimalcss.js https://songsear.ch/ https://songsear.ch/q/Have%20sweeter%20sound..%20now%20i%20see
```

In the output there are two distinct occurrences of:
```
html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}
```

**Comment by peterbe** [comment]
Ah! The reason is that `csso` can't merge across blocks separated by a `/*! important */` comment. E.g. If this is the input:
```css
html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}
/*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */
html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}
```
When running `csso.minify` the output is, the exact same as the input. 
However, if you remove that second line the output does become
```css
html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}
```
